---
title: Linear algebra in python
short_title: "Day 2, pt. 1: Linear algebra"
---

# Linear algebra in python

In the python ecosystem, linear algebra utilities can be found in:
+ The main `numpy` package
+ The `numpy.linalg` subpackage
+ The `scipy.linalg` subpackage

In [4]:
import numpy as np
import numpy.linalg as nla
import scipy.linalg as sla

Let's also import `matplotlib` for plotting purposes

In [22]:
import matplotlib.pyplot as plt

## Creating matrices and higher-dimensional arrays

From a `numpy` perspective, a matrix is just a nested numpy array for which dimensions align. For example:

In [4]:
A = np.array([[1, 4], [2, 3]])
print(A)

[[1 4]
 [2 3]]


In principle there is no reason to stop at 2 indices, e.g.,

In [7]:
M = np.array([[[1,2,3], [2,3,4]],[[-1, 0, 1], [-2, 0, 2]]])
print(M)

[[[ 1  2  3]
  [ 2  3  4]]

 [[-1  0  1]
  [-2  0  2]]]


Two useful ways to build matrices are (1) start with 1D array and reshape it into 2 (or higher) dimensions; (2) use built-in matrix-creating functions

In [8]:
B = np.arange(12).reshape(3, 4)
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
C = np.diag([1, 3, 5, 7])
print(C)

[[1 0 0 0]
 [0 3 0 0]
 [0 0 5 0]
 [0 0 0 7]]


Part of the matrix can be modified via indexed assignment

In [18]:
C[2][1] = -1
print(C)

[[ 1  0  0  0]
 [ 0  3  0  0]
 [ 0 -1  5  0]
 [ 0  0  0  7]]


## Element-wise operations

Element-wise arithmetics on arrays of matching dimensions

In [11]:
A = np.array([[1, 4], [2, 3]])
B = np.diag([1, -1])

In [12]:
A + B

array([[2, 4],
       [2, 2]])

In [13]:
A * B

array([[ 1,  0],
       [ 0, -3]])

Element-wise Arithmetics between arrays and scalars

In [15]:
A ** 2

array([[ 1, 16],
       [ 4,  9]])

In [16]:
B * 2

array([[ 2,  0],
       [ 0, -2]])

## Matrix multiplication

In [23]:
A = np.array([[1, 4], [2, 3]])
B = np.diag([1, -1])
X = np.array([-2, 3])

In [26]:
# applying a matrix on a (column) vector 
A @ X

array([10,  5])

In [27]:
# matrix multiplication
A @ B

array([[ 1, -4],
       [ 2, -3]])

## Eigenvalues and eigenvectors

There are four functions associated with matrix eigensystem:

+ `nla.eigvals()` solves the eigenvalues of a general matrix
+ `nla.eigvalsh()` solves the eigenvalues of a symmetric matrix
+ `nla.eig()` solves both eigenvalues and eigenvectors of a general matrix
+ `nla.eigh()` solves the eigenvalues and eigenvecto of a symmetric matrix

In [28]:
# eigensystem of a matrix
A = np.array([[1, 4], [2, 3]])
D, V = nla.eig(A)

In [29]:
print(D)
print(V)

[-1.  5.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [32]:
V @ np.diag(D) @ nla.inv(V)

array([[1., 4.],
       [2., 3.]])

In [33]:
A @ V[:, 1]

array([-3.53553391, -3.53553391])

In [34]:
D[1] * V[:, 1]

array([-3.53553391, -3.53553391])

## Cumulative exercise: Leslie matrix

The Leslie matrix describes how population structure changes with time. In one formulation, the matrix takes the general form:
\begin{bmatrix}
P_1 & F_1 & F_2 & \cdots & F_{N-1} \\
G_1 & P_2 & 0   & \cdots & 0 \\
0   & G_2 & P_3   & \cdots & 0 \\
\vdots & \vdots & \vdots & & \vdots \\
0 & \cdots & 0 & G_{N-1} & P_N
\end{bmatrix}

Given a population structure (counts of individual per age group) $\mathbf{n}_k = [n_{1,k}, n_{2,k}, \cdots, n_{N,k}]^T$ at time step $t(k)$, the population structure at time step $t(k+1)$ is given by $\mathbf{n}_{k+1} = L \, @ \, \mathbf{n}_k$

For concreteness, we will use the sea turtles data from [Crouse et.al., _Ecology_, 68(5), 1987](https://doi.org/10.2307/1939225), where, in the span of a year,

+ $\mathbf{P}$ = [0, 0.7370, 0.6610, 0.6907, 0, 0, 0.8089]
+ $\mathbf{G}$ = [0.6757, 0.0486, 0.0147, 0.0518, 0.8091, 0.8091]
+ $\mathbf{F}$ = [0, 0, 0, 0, 127, 4, 80] 

Where the stages represents:

In [24]:
stages = ["eggs, hatchlings", "small juveniles", "large juveniles", "subadults", 
          "novice breeders", "1st-yr remigrants", "mature breeders"]

In [7]:
# Function to build a Leslie matrix given per-age-class birthrate and per-age-class mortality

def make_Leslie_Matrix(F, P, G):
    M = np.diag(P) + np.diag(G, -1)
    M[0, 1:] = F
    return M

In [13]:
F = [0, 0, 0, 127, 4, 80]
P = [0, 0.7370, 0.6610, 0.6907, 0, 0, 0.8089]
G = [0.6757, 0.0486, 0.0147, 0.0518, 0.8091, 0.8091]

L = make_Leslie_Matrix(F, P, G)
print(L)

[[0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.270e+02 4.000e+00 8.000e+01]
 [6.757e-01 7.370e-01 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 4.860e-02 6.610e-01 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 1.470e-02 6.907e-01 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 5.180e-02 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 8.091e-01 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 8.091e-01 8.089e-01]]


**Exercise 1**: Consider a population starting with 5 novice breeder (stage 5) per area, track the number of individuals per area in the first 10 years

**Exercise 2**: Find the eigenvalues of the sea turtles Leslie matrix. Determine if, in the long term, the population would be growing, declining, or remain stable.

**Mathematical background**: Let $\lambda_1$ be the largest eigenvalue of the Leslie matrix $L$. Then:
+ $|\lambda_1| > 1$ implies a growing population
+ $|\lambda_1| < 1$ implies a decling population
+ $|\lambda_1| = 1$ implies a stable population