---
title: Linear algebra in python
short_title: "Day 2, pt. 1: Linear algebra"
---

# Linear algebra in python

In the python ecosystem, linear algebra utilities can be found in:
+ The main `numpy` package
+ The `numpy.linalg` subpackage
+ The `scipy.linalg` subpackage

In [1]:
import numpy as np
import numpy.linalg as nla
import scipy.linalg as sla

## Creating matrices and higher-dimensional arrays

From a `numpy` perspective, a matrix is just a nested numpy array for which dimensions align. For example:

In [4]:
A = np.array([[1, 4], [2, 3]])
print(A)

[[1 4]
 [2 3]]


In principle there is no reason to stop at 2 indices, e.g.,

In [7]:
M = np.array([[[1,2,3], [2,3,4]],[[-1, 0, 1], [-2, 0, 2]]])
print(M)

[[[ 1  2  3]
  [ 2  3  4]]

 [[-1  0  1]
  [-2  0  2]]]


Two useful ways to build matrices are (1) start with 1D array and reshape it into 2 (or higher) dimensions; (2) use built-in matrix-creating functions

In [8]:
B = np.arange(12).reshape(3, 4)
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
C = np.diag([1, 3, 5, 7])
print(C)

[[1 0 0 0]
 [0 3 0 0]
 [0 0 5 0]
 [0 0 0 7]]


Part of the matrix can be modified via indexed assignment

In [18]:
C[2][1] = -1
print(C)

[[ 1  0  0  0]
 [ 0  3  0  0]
 [ 0 -1  5  0]
 [ 0  0  0  7]]


## Element-wise operations

Element-wise arithmetics on arrays of matching dimensions

In [11]:
A = np.array([[1, 4], [2, 3]])
B = np.diag([1, -1])

In [12]:
A + B

array([[2, 4],
       [2, 2]])

In [13]:
A * B

array([[ 1,  0],
       [ 0, -3]])

Element-wise Arithmetics between arrays and scalars

In [15]:
A ** 2

array([[ 1, 16],
       [ 4,  9]])

In [16]:
B * 2

array([[ 2,  0],
       [ 0, -2]])

## Matrix multiplication

In [23]:
A = np.array([[1, 4], [2, 3]])
B = np.diag([1, -1])
X = np.array([-2, 3])

In [26]:
# applying a matrix on a (column) vector 
A @ X

array([10,  5])

In [27]:
# matrix multiplication
A @ B

array([[ 1, -4],
       [ 2, -3]])

## Eigenvalues and eigenvectors

There are four functions associated with matrix eigensystem:

+ `nla.eigvals()` solves the eigenvalues of a general matrix
+ `nla.eigvalsh()` solves the eigenvalues of a symmetric matrix
+ `nla.eig()` solves both eigenvalues and eigenvectors of a general matrix
+ `nla.eigh()` solves the eigenvalues and eigenvecto of a symmetric matrix

In [28]:
# eigensystem of a matrix
A = np.array([[1, 4], [2, 3]])
D, V = nla.eig(A)

In [29]:
print(D)
print(V)

[-1.  5.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [32]:
V @ np.diag(D) @ nla.inv(V)

array([[1., 4.],
       [2., 3.]])

In [33]:
A @ V[:, 1]

array([-3.53553391, -3.53553391])

In [34]:
D[1] * V[:, 1]

array([-3.53553391, -3.53553391])

## Cumulative example: Leslie Matrix